name: Arduino CI

on:
  push:
    paths:
      - 'eSW/FFRESW/FFRESW/FFRESW.ino'
      - 'eSW/libraries/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'eSW/FFRESW/FFRESW/FFRESW.ino'
      - 'eSW/libraries/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install specific version of arduino:avr core
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr@1.8.3

      - name: Copy custom libraries into Arduino CLI libraries folder
        run: |
          mkdir -p ~/Arduino/libraries
          cp -r eSW/libraries/* ~/Arduino/libraries/
          cp -r external/* ~/Arduino/libraries/

      - name: List libraries in Arduino folder
        run: |
          echo "Libraries in ~/Arduino/libraries:"
          ls ~/Arduino/libraries/

      - name: Clean Arduino build cache
        run: |
          rm -rf /home/runner/.cache/arduino/sketches/*

      - name: Compile Arduino Sketches
        uses: arduino/compile-sketches@v1.1.2
        with:
          fqbn: "arduino:avr:mega"
          libraries: |
            - name: "Ethernet"
            - name: "SD"
            - name: "Adafruit BusIO"
            - name: "Adafruit MCP9600 Library"
            - name: "ArduinoJson"
            - name: "FreeRTOS"
            - name: "frt"
            - name: "Vector"
          sketch-paths: |
            - eSW/FFRESW/FFRESW/FFRESW.ino
          verbose: true

      - name: Compile Arduino Sketches (CLI Version)
        run: |
          arduino-cli compile --verbose \
            --fqbn arduino:avr:mega \
            --libraries ~/Arduino/libraries \
            --export-binaries \
            eSW/FFRESW/FFRESW/FFRESW.ino

      - name: Debug - List compiled files in cache directory
        run: |
          echo "Listing compiled files in the Arduino cache directory"
          ls -R /home/runner/.cache/arduino/sketches/ | grep -E '\.(hex|bin|elf)$'

      - name: Install analysis tools
        run: sudo apt-get update && sudo apt-get install -y binutils

      - name: Generate ELF Analysis Report (Markdown)
        run: |
          mkdir -p elf-analysis
          for elf_file in $(find /home/runner/.cache/arduino/sketches/ -name '*.elf'); do
            base_name=$(basename "$elf_file" .elf)
            report_file="elf-analysis/${base_name}_report.md"
            echo "# ELF Analysis Report for ${base_name}.elf" > "$report_file"
            echo "" >> "$report_file"
            echo "## ELF Header" >> "$report_file"
            echo '```' >> "$report_file"
            readelf -h "$elf_file" >> "$report_file"
            echo '```' >> "$report_file"
            echo "## Section Headers" >> "$report_file"
            echo '```' >> "$report_file"
            readelf -S "$elf_file" >> "$report_file"
            echo '```' >> "$report_file"
            echo "## Symbols" >> "$report_file"
            echo '```' >> "$report_file"
            readelf -s "$elf_file" >> "$report_file"
            echo '```' >> "$report_file"
            echo "## Disassembly (First 100 lines)" >> "$report_file"
            echo '```' >> "$report_file"
            objdump -d "$elf_file" | head -n 100 >> "$report_file"
            echo '```' >> "$report_file"
          done

      - name: Upload ELF Analysis Report
        uses: actions/upload-artifact@v4
        with:
          name: elf-analysis-report
          path: elf-analysis/
          if-no-files-found: error
          compression-level: 6
          overwrite: true
          include-hidden-files: false

      - name: Upload Build Artifacts (HEX, BIN, ELF)
        uses: actions/upload-artifact@v4
        with:
          name: arduino-build-artifacts
          path: |
            /home/runner/.cache/arduino/sketches/**/*.hex
            /home/runner/.cache/arduino/sketches/**/*.bin
            /home/runner/.cache/arduino/sketches/**/*.elf
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false
