name: Arduino CI

on:
  push:
    paths:
      - 'eSW/FFRESW/FFRESW/FFRESW.ino'
      - 'eSW/libraries/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'eSW/FFRESW/FFRESW/FFRESW.ino'
      - 'eSW/libraries/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Copy custom libraries into Arduino CLI libraries folder
        run: |
          mkdir -p ~/Arduino/libraries
          cp -r eSW/libraries/* ~/Arduino/libraries/

      - name: List libraries in Arduino folder
        run: |
          echo "Libraries in ~/Arduino/libraries:"
          ls ~/Arduino/libraries/

      - name: Compile Arduino Sketches
        uses: arduino/compile-sketches@v1.1.2
        with:
          fqbn: "arduino:avr:mega"
          libraries: |
            - name: "Adafruit BusIO"
            - name: "Adafruit MCP9600 Library"
            - name: "ArduinoJson"
            - name: "ArduinoSTL"
            - name: "FreeRTOS"
            - name: "frt"
            - name: "Vector"
          sketch-paths: |
            - eSW/FFRESW/FFRESW/FFRESW.ino
          verbose: true
