name: Arduino CI

on:
  push:
    paths:
      - 'eSW/FFRESW/FFRESW/FFRESW.ino'
      - 'eSW/libraries/**'
  pull_request:
    paths:
      - 'eSW/FFRESW/FFRESW/FFRESW.ino'
      - 'eSW/libraries/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Copy custom libraries into Arduino CLI libraries folder
        run: |
          mkdir -p ~/.arduino/libraries
          cp -r eSW/libraries/* ~/.arduino/libraries/

      - name: Install external libraries
        run: |
          arduino-cli lib install "Adafruit BusIO"
          arduino-cli lib install "Adafruit MCP9600 Library"
          arduino-cli lib install "ArduinoJson"
          arduino-cli lib install "ArduinoSTL"
          arduino-cli lib install "FreeRTOS"
          arduino-cli lib install "frt"
          arduino-cli lib install "Vector"

      - name: Compile Arduino Sketches
        uses: arduino/compile-sketches@v1.1.2
        with:
          fqbn: "arduino:avr:mega"
          libraries: |
            - name: "Adafruit BusIO"
            - name: "Adafruit MCP9600 Library"
            - name: "ArduinoJson"
            - name: "ArduinoSTL"
            - name: "FreeRTOS"
            - name: "frt"
            - name: "Vector"
            - name: "calcModule"
            - name: "sensorModule"
            - name: "comModule"
            - name: "reportSystem"
            - name: "jsonModule"
            - name: "timeModule"
            - name: "serialMenu"
            - name: "flyback"
            - name: "logManager"
            - name: "vacControl"
          sketch-paths: |
            - eSW/FFRESW/FFRESW/FFRESW.ino
          verbose: true
