name: Arduino CI

on:
  push:
    paths:
      - 'eSW/FFRESW/FFRESW/FFRESW.ino'
      - 'eSW/libraries/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'eSW/FFRESW/FFRESW/FFRESW.ino'
      - 'eSW/libraries/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install specific version of arduino:avr core
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr@1.8.3

      - name: Copy custom libraries into Arduino CLI libraries folder
        run: |
          mkdir -p ~/Arduino/libraries
          cp -r eSW/libraries/* ~/Arduino/libraries/
          cp -r external/* ~/Arduino/libraries/

      - name: List libraries in Arduino folder
        run: |
          echo "Libraries in ~/Arduino/libraries:"
          ls ~/Arduino/libraries/

      - name: Compile Arduino Sketches
        uses: arduino/compile-sketches@v1.1.2
        with:
          fqbn: "arduino:avr:mega"
          libraries: |
            - name: "Ethernet"
            - name: "SD"
            - name: "Adafruit BusIO"
            - name: "Adafruit MCP9600 Library"
            - name: "ArduinoJson"
            - name: "FreeRTOS"
            - name: "frt"
            - name: "Vector"
          sketch-paths: |
            - eSW/FFRESW/FFRESW/FFRESW.ino
          verbose: true

      - name: Verify if files are created and print directory content
        run: |
          echo "Checking build output directory..."
          # List the files in the build directory to ensure the compiled files are there
          find ~/.arduino15 -type f -name "*.elf" -o -name "*.hex"

      - name: Collect FFRESW .hex and .elf file paths
        id: collect_files
        run: |
          # Search for the .hex and .elf files related to the FFRESW.ino sketch
          HEX_FILE=$(find ~/.arduino15 -type f -name "FFRESW*.hex" | head -n 1)
          ELF_FILE=$(find ~/.arduino15 -type f -name "FFRESW*.elf" | head -n 1)
          echo "HEX File: $HEX_FILE"
          echo "ELF File: $ELF_FILE"
          echo "hex_file=$HEX_FILE" >> $GITHUB_ENV
          echo "elf_file=$ELF_FILE" >> $GITHUB_ENV

      - name: Upload FFRESW .hex and .elf files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-arduino-files
          path: |
            ${{ env.hex_file }}
            ${{ env.elf_file }}

      - name: Print file sizes for build stats
        run: |
          echo "File Sizes:"
          if [ -f "${{ env.elf_file }}" ]; then
            ELF_SIZE=$(stat -c %s "${{ env.elf_file }}")
            echo "ELF File Size: $ELF_SIZE bytes"
          else
            echo "ELF file not found."
          fi
          
          if [ -f "${{ env.hex_file }}" ]; then
            HEX_SIZE=$(stat -c %s "${{ env.hex_file }}")
            echo "HEX File Size: $HEX_SIZE bytes"
          else
            echo "HEX file not found."
          fi
          
          echo "Total size: $(($ELF_SIZE + $HEX_SIZE)) bytes"
